set nocompatible              " be iMproved, required
filetype off                  " required
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()  " set the runtime path to include Vundle and initialize
Plugin 'gmarik/Vundle.vim' " let Vundle manage Vundle, required
" All Plugins

" Scala
Bundle 'derekwyatt/vim-scala'
" Purescipt
Bundle 'raichoo/purescript-vim'
" CoffeeScript
Plugin 'kchmck/vim-coffee-script'
" Less
Bundle 'groenewege/vim-less'
" Javascript (better syntax)
Plugin 'pangloss/vim-javascript'

" Ctrl-P -- search by filename
Bundle 'kien/ctrlp.vim'
" Ack -- grep -R, optimized
Bundle 'mileszs/ack.vim'
" toggles btwn relative and absolute line numbering
Bundle 'myusuf3/numbers.vim'
" automatically close open html/xml tags with ctrl+_
Plugin 'vim-scripts/closetag.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" End of Vundle


" Run mkdir -p ~/.vim/backup ~/vim/swp ~/.vim/undo
set undodir=~/.vim/undo//
set backupdir=~/.vim/backup//
set directory=~/.vim/swp//


syntax on

set encoding=utf-8        " Necessary to show Unicode glyphs

set scrolloff=4           " Scroll this many lines boyond cursor

set number                " Show line numbers
set relativenumber        " Show relative line numbers

set incsearch             " Incremental search
set ignorecase            " Ignore case in search ...
set smartcase             "  unless upper case chars occur in search string

set backspace=indent,eol,start  " Allows bs'ing across these things

set history=200           " Remember 200 lines

set wrap

" Tab settings
set expandtab       " Replace tabs with space
set tabstop=2       " (defaults)
set softtabstop=2
set shiftwidth=2

autocmd Filetype python setlocal tabstop=4 softtabstop=4 shiftwidth=4
autocmd Filetype html setlocal tabstop=2 softtabstop=2 shiftwidth=2


" set t_Co=256
set background=dark
hi Search ctermfg=152
hi Search ctermbg=236

" tone down line numbers, current line is a bit brighter
highlight LineNr ctermfg=237
highlight CursorLineNr ctermfg=245

set wildignore+=*/target/*,*.swo,*.swp,*/dist/*,*/node_modules/*,*/lib/*

" Map w!! to write file with sudo, when forgot to open with sudo.
cmap w!! w !sudo tee % >/dev/null

" Makes the cursor stay in place as you leave insert mode
autocmd InsertLeave * :normal `^
" XXX Attempt below breaks arrow keys in insert mode in some envs/contexts!!!
" inoremap <Esc> <Esc>l

" In normal mode, map <tab>,<shift+tab> to next,prev tab
nnoremap <C-I> :tabn<CR>
nnoremap <S-Tab> :tabp<CR>

" In visual mode, map <tab>,<shift+tab> to indent,unindent
vnoremap <C-I> >
vnoremap <S-Tab> <

" In insert mode, map <shift+tab> to un-indent
inoremap <S-Tab> <Esc><<i

" In normal mode, map <'> to CtrlP
nnoremap ' :CtrlP<CR>

" In normal mode, map <ctrl+/> to toggle search highlightling
nnoremap <C-l> :set hlsearch!<CR>

" Single semi-colon <;> maps to full on colon <:>
nnoremap ;  :

" Double semi-colon <;;> maps to Save
nnoremap ;; :w<CR>

" set omnifunc=syntaxcomplete

" Automatically strip whitespace on save
autocmd BufWritePre * :%s/\s\+$//e

" Ctrl-P : open in new tab by default
let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<c-t>'],
    \ 'AcceptSelection("t")': ['<cr>', '<2-LeftMouse>'],
    \ }


" Ack.vim settings
if executable('ag')    " use ag if installed
  let g:ackprg = 'ag --vimgrep'
endif

let g:ack_autoclose = 1

" Ack convenience
noremap + :LAck "\W<cword>\W"<CR>
noremap - :lnext<CR>
noremap _ :lprevious<CR>

colorscheme tomorrow-night
