set nocompatible              " be iMproved, required
filetype off                  " required
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()  " set the runtime path to include Vundle and initialize
Plugin 'gmarik/Vundle.vim' " let Vundle manage Vundle, required
" All Plugins

" Javascript (better syntax)
Plugin 'pangloss/vim-javascript'
" Scala
Bundle 'derekwyatt/vim-scala'
" SQL
Plugin 'magicalbanana/vim-sql-syntax'
" C/#
Plugin 'OrangeT/vim-csharp'
" FreeMarker Templates
Plugin 'chaquotay/ftl-vim-syntax'

" Ctrl-P -- search by filename
Bundle 'kien/ctrlp.vim'
" Ack -- grep -R, optimized
Bundle 'mileszs/ack.vim'
" toggles btwn relative and absolute line numbering
Bundle 'myusuf3/numbers.vim'
" automatically close open html/xml tags with ctrl+_
Plugin 'vim-scripts/closetag.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" End of Vundle


" Run mkdir -p ~/.vim/backup ~/vim/swp ~/.vim/undo
set undodir=~/.vim/undo//
set backupdir=~/.vim/backup//
set directory=~/.vim/swp//


syntax on

set encoding=utf-8        " Necessary to show Unicode glyphs

set scrolloff=4           " Scroll this many lines boyond cursor

set number                " Show line numbers
set relativenumber        " Show relative line numbers

set incsearch             " Incremental search
set ignorecase            " Ignore case in search ...
set smartcase             "  unless upper case chars occur in search string

set backspace=indent,eol,start  " Allows bs'ing across these things

set history=200           " Remember 200 lines

set wrap

" Tab settings
set expandtab       " Replace tabs with space
set tabstop=2       " (defaults)
set softtabstop=2
set shiftwidth=2

autocmd Filetype python setlocal tabstop=4 softtabstop=4 shiftwidth=4
autocmd Filetype html setlocal tabstop=2 softtabstop=2 shiftwidth=2

" Additional FileExtension->SyntaxHighlighting mappings
autocmd BufNewFile,BufRead *.scalas set filetype=scala
autocmd BufNewFile,BufRead *.avsc set filetype=javascript
autocmd BufNewFile,BufRead *.json set filetype=javascript
autocmd BufNewFile,BufRead .babelrc set filetype=javascript

" set t_Co=256
set background=dark
hi Search ctermfg=152
hi Search ctermbg=236

" tone down line numbers, current line is a bit brighter
highlight LineNr ctermfg=237
highlight CursorLineNr ctermfg=245

set wildignore+=*/target/*,*.swo,*.swp,*/dist/*,*/node_modules/*,*/lib/*,*/export/*

" == Bindings ==
" In visual and normal modes, map T => J => N => K => L => T
" t = til
" T = prev. til
" j = move down
" J = join lines
" n = next search
" N = prev. search
" k = move up
" K = open manpage
" l = move right
" L = move to bottom of window
nnoremap t j
nnoremap T J
vnoremap t j
vnoremap T J

nnoremap n k
nnoremap N K
vnoremap n k
vnoremap N K

nnoremap s l
nnoremap S L
vnoremap s l
vnoremap S L

nnoremap k s
nnoremap K S
vnoremap k s
vnoremap K S

nnoremap j n
nnoremap J N
vnoremap j n
vnoremap J N

nnoremap l t
nnoremap L T
vnoremap l l
vnoremap L T

" In normal mode, single semi-colon <;> maps to full on colon <:>
nnoremap ; :

" In all modes, map double semi-colon <;;> maps back to semi-colon <;>
noremap ;; ;

" Map command <qj> to <wq>
cnoreabbrev <expr> qj ((getcmdtype() is# ':' && getcmdline() is# 'qj')?('wq'):('qj'))

" Map w!! to write file with sudo, when forgot to open with sudo.
cmap w!! w !sudo tee % >/dev/null

" Makes the cursor stay in place as you leave insert mode
autocmd InsertLeave * :normal `^

" In normal mode, map <tab>,<shift+tab> to next,prev tab
nnoremap <C-I> :tabn<CR>
nnoremap <S-Tab> :tabp<CR>

" In visual mode, map <tab>,<shift+tab> to indent,unindent
vnoremap <C-I> >
vnoremap <S-Tab> <

" In insert mode, map <shift+tab> to un-indent
inoremap <S-Tab> <Esc><<i

" In normal mode, map <'> to CtrlP
nnoremap ' :CtrlP<CR>

" In normal mode, map <ctrl+/> to toggle search highlightling
nnoremap <C-l> :set hlsearch!<CR>


" set omnifunc=syntaxcomplete

" Automatically strip whitespace on save
"autocmd BufWritePre * :%s/\s\+$//e

" Ctrl-P : open in new tab by default
let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<c-t>'],
    \ 'AcceptSelection("t")': ['<cr>', '<2-LeftMouse>'],
    \ }


" Ack.vim settings
if executable('ag')    " use ag if installed
  let g:ackprg = 'ag --nogroup --nocolor --column'
endif

let g:ack_autoclose = 1

" Ack convenience
noremap + :LAck "\W<cword>\W"<CR>
noremap - :lnext<CR>
noremap _ :lprevious<CR>

" colorscheme badwolf
colorscheme jellybeans
