#!/usr/bin/env zsh

src_dir=${ZSH_SOURCE:-"$(dirname $0)/dotfiles/zsh"}
source "$src_dir"/aliases.zsh
source "$src_dir"/key_bindings.zsh
source "$src_dir"/misc.zsh
source "$src_dir"/prompt.zsh

if [ -r "local.zshrc" ]; then
  source "local.zshrc"
fi
